name: Windows

on: [push, pull_request]

jobs:
  Core:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run core test
      run: rebview.exe -qws tests\run-core-tests.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: core-test-log
        path: quick-test/quick-test.log

  Core-Release:

    runs-on: windows-latest
   
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run core test
      run: rebview.exe -qws tests\run-core-tests.r --batch --release
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: core-test-log
        path: quick-test/quick-test.log

  Core-Debug:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run core test
      run: rebview.exe -qws tests\run-core-tests.r --batch --debug
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: core-debug-test-log
        path: quick-test/quick-test.log

  View:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run view test
      run: rebview.exe -qws tests\run-view-tests.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: view-test-log
        path: quick-test/quick-test.log

  Regression:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run regression test
      run: rebview.exe -qws tests\run-regression-tests.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: regression-test-log
        path: quick-test/quick-test.log

  Each-Mode:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run each test
      run: rebview.exe -qws tests\run-core-tests.r --ci-each
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: each-test-log
        path: quick-test/quick-test.log

  Each-Mode-Debug:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run each test
      run: rebview.exe -qws tests\run-core-tests.r --ci-each --debug
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: each-debug-test-log
        path: quick-test/quick-test.log

  Red-System-Test:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: setup red repo
      run: |
        $url = "http://static.red-lang.org/build/rebview.exe"
        $output = "$Env:GITHUB_WORKSPACE\rebview.exe"
        (New-Object System.Net.WebClient).DownloadFile($url, $output)
    - name: run Red/System test
      run: rebview.exe -qws system\tests\run-all.r --batch
      shell: cmd

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: rs-test-log
        path: quick-test/quick-test.log